//------------------------------------------------------------------------------
//	<auto-generated>
//		This code was generated from a template.
//		Manual changes will be overwritten if the code is regenerated.
//	</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

#if HWINTRINSICS
using System.Runtime.Intrinsics.X86;
#endif

namespace Blake2Fast
{
	unsafe internal partial struct Blake2sContext : IBlake2Incremental
	{
		public const int WordSize = sizeof(uint);
		public const int BlockWords = 16;
		public const int BlockBytes = BlockWords * WordSize;
		public const int HashWords = 8;
		public const int HashBytes = HashWords * WordSize;
		public const int MaxKeyBytes = HashBytes;

		private fixed byte b[BlockBytes];
		private fixed uint h[HashWords];
		private fixed uint t[2];
		private fixed uint f[2];
		private uint c;
		private uint outlen;

		private static ReadOnlySpan<byte> ivle => new byte[] {
			0x67, 0xE6, 0x09, 0x6A,
			0x85, 0xAE, 0x67, 0xBB,
			0x72, 0xF3, 0x6E, 0x3C,
			0x3A, 0xF5, 0x4F, 0xA5,
			0x7F, 0x52, 0x0E, 0x51,
			0x8C, 0x68, 0x05, 0x9B,
			0xAB, 0xD9, 0x83, 0x1F,
			0x19, 0xCD, 0xE0, 0x5B
		};

#if HWINTRINSICS
		private static ReadOnlySpan<byte> rormask => new byte[] {
			2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, //r16
			1, 2, 3, 0, 5, 6, 7, 4, 9, 10, 11, 8, 13, 14, 15, 12  //r8
		};
#endif

		public int DigestLength => (int)outlen;

		private void compress(ref byte input, uint offs, uint cb)
		{
			uint inc = Math.Min(cb, BlockBytes);

			fixed (byte* pinput = &input)
			fixed (Blake2sContext* s = &this)
			{
				uint* sh = s->h;
				byte* pin = pinput + offs;
				byte* end = pin + cb;

				do
				{
					t[0] += inc;
					if (t[0] < inc)
						t[1]++;

					uint* m = (uint*)pin;
#if HWINTRINSICS
					if (Sse41.IsSupported)
						mixSse41(sh, m);
					else
#endif
						mixScalar(sh, m);

					pin += inc;
				} while (pin < end);
			}
		}

		public void Init(int digestLength = HashBytes, ReadOnlySpan<byte> key = default)
		{
			uint keylen = (uint)key.Length;

			if (!BitConverter.IsLittleEndian) ThrowHelper.NoBigEndian();
			if (digestLength == 0 || (uint)digestLength > HashBytes) ThrowHelper.DigestInvalidLength(HashBytes);
			if (keylen > MaxKeyBytes) ThrowHelper.KeyTooLong(MaxKeyBytes);

			outlen = (uint)digestLength;

			Unsafe.CopyBlock(ref Unsafe.As<uint, byte>(ref h[0]), ref MemoryMarshal.GetReference(ivle), HashBytes);
			h[0] ^= 0x01010000u ^ (keylen << 8) ^ outlen;

			if (keylen != 0)
			{
				Unsafe.CopyBlockUnaligned(ref b[0], ref MemoryMarshal.GetReference(key), keylen);
				c = BlockBytes;
			}
		}

		public void Update(ReadOnlySpan<byte> input)
		{
			if (f[0] != 0) ThrowHelper.HashFinalized();

			uint consumed = 0;
			uint remaining = (uint)input.Length;
			ref byte rinput = ref MemoryMarshal.GetReference(input);

			uint blockrem = BlockBytes - c;
			if ((c != 0) && (remaining > blockrem))
			{
				if (blockrem != 0)
					Unsafe.CopyBlockUnaligned(ref b[c], ref rinput, blockrem);

				c = 0;
				compress(ref b[0], 0, BlockBytes);
				consumed += blockrem;
				remaining -= blockrem;
			}

			if (remaining > BlockBytes)
			{
				uint cb = (remaining - 1) & ~((uint)BlockBytes - 1);
				compress(ref rinput, consumed, cb);
				consumed += cb;
				remaining -= cb;
			}

			if (remaining != 0)
			{
				Unsafe.CopyBlockUnaligned(ref b[c], ref Unsafe.Add(ref rinput, (int)consumed), remaining);
				c += remaining;
			}
		}

		public void Update<T>(ReadOnlySpan<T> input) where T : struct
		{
			ThrowHelper.ThrowIfIsRefOrContainsRefs<T>();

			Update(MemoryMarshal.AsBytes(input));
		}

		public void Update<T>(T input) where T : struct
		{
			ThrowHelper.ThrowIfIsRefOrContainsRefs<T>();

			if (Unsafe.SizeOf<T>() > BlockBytes - c)
			{
#if BUILTIN_SPAN
				Update(MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<T, byte>(ref input), Unsafe.SizeOf<T>()));
#else
				Span<byte> buff = stackalloc byte[Unsafe.SizeOf<T>()];
				Unsafe.WriteUnaligned(ref buff[0], input);
				Update(buff);
#endif
				return;
			}

			if (f[0] != 0) ThrowHelper.HashFinalized();

			Unsafe.WriteUnaligned(ref b[c], input);
			c += (uint)Unsafe.SizeOf<T>();
		}

		private void finish(Span<byte> hash)
		{
			if (f[0] != 0) ThrowHelper.HashFinalized();

			if (c < BlockBytes)
				Unsafe.InitBlockUnaligned(ref b[c], 0, BlockBytes - c);

			f[0] = ~0u;
			compress(ref b[0], 0, c);

			Unsafe.CopyBlockUnaligned(ref hash[0], ref Unsafe.As<uint, byte>(ref h[0]), outlen);
		}

		public byte[] Finish()
		{
			byte[] hash = new byte[outlen];
			finish(hash);

			return hash;
		}

		public bool TryFinish(Span<byte> output, out int bytesWritten)
		{
			if ((uint)output.Length < outlen)
			{
				bytesWritten = 0;
				return false;
			}

			finish(output);
			bytesWritten = (int)outlen;
			return true;
		}
	}
}
