//------------------------------------------------------------------------------
//	<auto-generated>
//		This code was generated from a template.
//		Manual changes to this file will be overwritten if the code is regenerated.
//	</auto-generated>
//------------------------------------------------------------------------------

#if USE_INTRINSICS
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Runtime.CompilerServices;

namespace SauceControl.Blake2Fast
{
	unsafe internal partial struct Blake2sContext
	{
		private static readonly byte[] rormask = new byte[] {
			1, 2, 3, 0, 5, 6, 7, 4, 9, 10, 11, 8, 13, 14, 15, 12, //r8
			2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13 //r16
		};

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void g1(ref Vector128<uint> row1, ref Vector128<uint> row2, ref Vector128<uint> row3, ref Vector128<uint> row4, in Vector128<uint> b0, in Vector128<sbyte> r16)
		{
			row1 = Sse2.Add(Sse2.Add(row1, b0), row2);
			row4 = Sse2.Xor(row4, row1);
#if OLD_INTRINSICS
			row4 = Sse.StaticCast<sbyte, uint>(Ssse3.Shuffle(Sse.StaticCast<uint, sbyte>(row4), r16));
#else
			row4 = Ssse3.Shuffle(row4.AsSByte(), r16).AsUInt32();
#endif

			row3 = Sse2.Add(row3, row4);
			row2 = Sse2.Xor(row2, row3);
			row2 = Sse2.Xor(Sse2.ShiftRightLogical(row2, 12), Sse2.ShiftLeftLogical(row2, 20));
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void g2(ref Vector128<uint> row1, ref Vector128<uint> row2, ref Vector128<uint> row3, ref Vector128<uint> row4, in Vector128<uint> b0, in Vector128<sbyte> r8)
		{
			row1 = Sse2.Add(Sse2.Add(row1, b0), row2);
			row4 = Sse2.Xor(row4, row1);
#if OLD_INTRINSICS
			row4 = Sse.StaticCast<sbyte, uint>(Ssse3.Shuffle(Sse.StaticCast<uint, sbyte>(row4), r8));
#else
			row4 = Ssse3.Shuffle(row4.AsSByte(), r8).AsUInt32();
#endif

			row3 = Sse2.Add(row3, row4);
			row2 = Sse2.Xor(row2, row3);
			row2 = Sse2.Xor(Sse2.ShiftRightLogical(row2, 7), Sse2.ShiftLeftLogical(row2, 25));
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void diagonalize(ref Vector128<uint> row1, ref Vector128<uint> row2, ref Vector128<uint> row3, ref Vector128<uint> row4)
		{
			row4 = Sse2.Shuffle(row4, 0b_10_01_00_11);
			row3 = Sse2.Shuffle(row3, 0b_01_00_11_10);
			row2 = Sse2.Shuffle(row2, 0b_00_11_10_01);
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void undiagonalize(ref Vector128<uint> row1, ref Vector128<uint> row2, ref Vector128<uint> row3, ref Vector128<uint> row4)
		{
			row4 = Sse2.Shuffle(row4, 0b_00_11_10_01);
			row3 = Sse2.Shuffle(row3, 0b_01_00_11_10);
			row2 = Sse2.Shuffle(row2, 0b_10_01_00_11);
		}

		unsafe private static void mixSse41(Blake2sContext* s, uint* m)
		{
			var row1 = Sse2.LoadVector128(s->h);
			var row2 = Sse2.LoadVector128(s->h + 4);

			var row3 = Sse2.LoadVector128(s->viv);
			var row4 = Sse2.LoadVector128(s->viv + 4);

			row4 = Sse2.Xor(row4, Sse2.LoadVector128(s->t)); // reads into f[] as well

			var r8 = Sse2.LoadVector128((sbyte*)s->vrm);
			var r16 = Sse2.LoadVector128((sbyte*)s->vrm + 16);

			var m0 = Sse2.LoadVector128(m);
			var m1 = Sse2.LoadVector128(m + 4);
			var m2 = Sse2.LoadVector128(m + 8);
			var m3 = Sse2.LoadVector128(m + 12);

			//ROUND 1
#if OLD_INTRINSICS
			var b0 = Sse.StaticCast<float, uint>(Sse.Shuffle(Sse.StaticCast<uint, float>(m0), Sse.StaticCast<uint, float>(m1), 0b_10_00_10_00));
#else
			var b0 = Sse.Shuffle(m0.AsSingle(), m1.AsSingle(), 0b_10_00_10_00).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			b0 = Sse.StaticCast<float, uint>(Sse.Shuffle(Sse.StaticCast<uint, float>(m0), Sse.StaticCast<uint, float>(m1), 0b_11_01_11_01));
#else
			b0 = Sse.Shuffle(m0.AsSingle(), m1.AsSingle(), 0b_11_01_11_01).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			b0 = Sse.StaticCast<float, uint>(Sse.Shuffle(Sse.StaticCast<uint, float>(m2), Sse.StaticCast<uint, float>(m3), 0b_10_00_10_00));
#else
			b0 = Sse.Shuffle(m2.AsSingle(), m3.AsSingle(), 0b_10_00_10_00).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			b0 = Sse.StaticCast<float, uint>(Sse.Shuffle(Sse.StaticCast<uint, float>(m2), Sse.StaticCast<uint, float>(m3), 0b_11_01_11_01));
#else
			b0 = Sse.Shuffle(m2.AsSingle(), m3.AsSingle(), 0b_11_01_11_01).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 2
#if OLD_INTRINSICS
			var t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(m2), 0b_00_00_11_00));
#else
			var t0 = Sse41.Blend(m1.AsUInt16(), m2.AsUInt16(), 0b_00_00_11_00).AsUInt32();
#endif
			var t1 = Sse2.ShiftLeftLogical128BitLane(m3, 4);
#if OLD_INTRINSICS
			var t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_11_11_00_00));
#else
			var t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_11_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_01_00_11);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.Shuffle(m2, 0b_00_00_10_00);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(m3), 0b_11_00_00_00));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_11_11_00_00));
#else
			t1 = Sse41.Blend(m1.AsUInt16(), m3.AsUInt16(), 0b_11_00_00_00).AsUInt32();
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_11_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_11_00_01);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

			t0 = Sse2.ShiftLeftLogical128BitLane(m1, 4);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m2), Sse.StaticCast<uint, ushort>(t0), 0b_00_11_00_00));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(t1), 0b_11_11_00_00));
#else
			t1 = Sse41.Blend(m2.AsUInt16(), t0.AsUInt16(), 0b_00_11_00_00).AsUInt32();
			t2 = Sse41.Blend(m0.AsUInt16(), t1.AsUInt16(), 0b_11_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_11_00_01);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackHigh(m0, m1);
			t1 = Sse2.ShiftLeftLogical128BitLane(m3, 4);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_11_00));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_11_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_11_00_01);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 3
			t0 = Sse2.UnpackHigh(m2, m3);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m3), Sse.StaticCast<uint, ushort>(m1), 0b_00_00_11_00));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_11_11));
#else
			t1 = Sse41.Blend(m3.AsUInt16(), m1.AsUInt16(), 0b_00_00_11_00).AsUInt32();
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_11_01_00_10);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackLow(m2, m0);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(m0), 0b_11_11_00_00));
#else
			t1 = Sse41.Blend(t0.AsUInt16(), m0.AsUInt16(), 0b_11_11_00_00).AsUInt32();
#endif
			t2 = Sse2.ShiftLeftLogical128BitLane(m3, 8);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t2), 0b_11_00_00_00));
#else
			b0 = Sse41.Blend(t1.AsUInt16(), t2.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m2), 0b_00_11_11_00));
#else
			t0 = Sse41.Blend(m0.AsUInt16(), m2.AsUInt16(), 0b_00_11_11_00).AsUInt32();
#endif
			t1 = Sse2.ShiftRightLogical128BitLane(m1, 12);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_00_11));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_00_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_01_00_11_10);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.ShiftLeftLogical128BitLane(m3, 4);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m1), 0b_00_11_00_11));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_11_00_00_00));
#else
			t1 = Sse41.Blend(m0.AsUInt16(), m1.AsUInt16(), 0b_00_11_00_11).AsUInt32();
			t2 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_00_01_10_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 4
			t0 = Sse2.UnpackHigh(m0, m1);
			t1 = Sse2.UnpackHigh(t0, m2);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(m3), 0b_00_00_11_00));
#else
			t2 = Sse41.Blend(t1.AsUInt16(), m3.AsUInt16(), 0b_00_00_11_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_11_01_00_10);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.ShiftLeftLogical128BitLane(m2, 8);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m3), Sse.StaticCast<uint, ushort>(m0), 0b_00_00_11_00));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_11_00_00_00));
#else
			t1 = Sse41.Blend(m3.AsUInt16(), m0.AsUInt16(), 0b_00_00_11_00).AsUInt32();
			t2 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_00_01_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m1), 0b_00_00_11_11));
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(m3), 0b_11_00_00_00));
#else
			t0 = Sse41.Blend(m0.AsUInt16(), m1.AsUInt16(), 0b_00_00_11_11).AsUInt32();
			t1 = Sse41.Blend(t0.AsUInt16(), m3.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t1, 0b_11_00_01_10);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackLow(m0, m2);
			t1 = Sse2.UnpackHigh(m1, m2);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(t1), Sse.StaticCast<uint, ulong>(t0)));
#else
			b0 = Sse2.UnpackLow(t1.AsUInt64(), t0.AsUInt64()).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 5
#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(m1), Sse.StaticCast<uint, ulong>(m2)));
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m0), Sse.StaticCast<uint, ulong>(m2)));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_11_00_11));
#else
			t0 = Sse2.UnpackLow(m1.AsUInt64(), m2.AsUInt64()).AsUInt32();
			t1 = Sse2.UnpackHigh(m0.AsUInt64(), m2.AsUInt64()).AsUInt32();
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_11_00_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_00_01_11);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m1), Sse.StaticCast<uint, ulong>(m3)));
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(m0), Sse.StaticCast<uint, ulong>(m1)));
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_11_00_11));
#else
			t0 = Sse2.UnpackHigh(m1.AsUInt64(), m3.AsUInt64()).AsUInt32();
			t1 = Sse2.UnpackLow(m0.AsUInt64(), m1.AsUInt64()).AsUInt32();
			b0 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_11_00_11).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m3), Sse.StaticCast<uint, ulong>(m1)));
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m2), Sse.StaticCast<uint, ulong>(m0)));
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_00_11_00_11));
#else
			t0 = Sse2.UnpackHigh(m3.AsUInt64(), m1.AsUInt64()).AsUInt32();
			t1 = Sse2.UnpackHigh(m2.AsUInt64(), m0.AsUInt64()).AsUInt32();
			b0 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_00_11_00_11).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m2), 0b_00_00_00_11));
#else
			t0 = Sse41.Blend(m0.AsUInt16(), m2.AsUInt16(), 0b_00_00_00_11).AsUInt32();
#endif
			t1 = Sse2.ShiftLeftLogical128BitLane(t0, 8);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(m3), 0b_00_00_11_11));
#else
			t2 = Sse41.Blend(t1.AsUInt16(), m3.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_01_10_00_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 6
			t0 = Sse2.UnpackHigh(m0, m1);
			t1 = Sse2.UnpackLow(m0, m2);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(t0), Sse.StaticCast<uint, ulong>(t1)));
#else
			b0 = Sse2.UnpackLow(t0.AsUInt64(), t1.AsUInt64()).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.ShiftRightLogical128BitLane(m2, 4);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m3), 0b_00_00_00_11));
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_00_11_11_00));
#else
			t1 = Sse41.Blend(m0.AsUInt16(), m3.AsUInt16(), 0b_00_00_00_11).AsUInt32();
			b0 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_00_11_11_00).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(m0), 0b_00_00_11_00));
#else
			t0 = Sse41.Blend(m1.AsUInt16(), m0.AsUInt16(), 0b_00_00_11_00).AsUInt32();
#endif
			t1 = Sse2.ShiftRightLogical128BitLane(m3, 4);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_11_00_00));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_01_10_11_00);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(m1), Sse.StaticCast<uint, ulong>(m2)));
#else
			t0 = Sse2.UnpackLow(m1.AsUInt64(), m2.AsUInt64()).AsUInt32();
#endif
			t1= Sse2.Shuffle(m3, 0b_00_10_00_01);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_11_00_11));
#else
			b0 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_11_00_11).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 7
			t0 = Sse2.ShiftLeftLogical128BitLane(m1, 12);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m3), 0b_00_11_00_11));
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_11_00_00_00));
#else
			t1 = Sse41.Blend(m0.AsUInt16(), m3.AsUInt16(), 0b_00_11_00_11).AsUInt32();
			b0 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m3), Sse.StaticCast<uint, ushort>(m2), 0b_00_11_00_00));
#else
			t0 = Sse41.Blend(m3.AsUInt16(), m2.AsUInt16(), 0b_00_11_00_00).AsUInt32();
#endif
			t1 = Sse2.ShiftRightLogical128BitLane(m1, 4);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_00_11));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_00_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_10_01_11_00);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(m0), Sse.StaticCast<uint, ulong>(m2)));
#else
			t0 = Sse2.UnpackLow(m0.AsUInt64(), m2.AsUInt64()).AsUInt32();
#endif
			t1 = Sse2.ShiftRightLogical128BitLane(m1, 4);
#if OLD_INTRINSICS
			b0 = Sse2.Shuffle(Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_11_00)), 0b_10_11_01_00);
#else
			b0 = Sse2.Shuffle(Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_11_00).AsUInt32(), 0b_10_11_01_00);
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackHigh(m1, m2);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m0), Sse.StaticCast<uint, ulong>(t0)));
#else
			t1 = Sse2.UnpackHigh(m0.AsUInt64(), t0.AsUInt64()).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t1, 0b_11_00_01_10);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 8
			t0 = Sse2.UnpackHigh(m0, m1);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(m3), 0b_00_00_11_11));
#else
			t1 = Sse41.Blend(t0.AsUInt16(), m3.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t1, 0b_10_00_11_01);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m2), Sse.StaticCast<uint, ushort>(m3), 0b_00_11_00_00));
#else
			t0 = Sse41.Blend(m2.AsUInt16(), m3.AsUInt16(), 0b_00_11_00_00).AsUInt32();
#endif
			t1 = Sse2.ShiftRightLogical128BitLane(m0, 4);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_00_11));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_00_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_01_00_10_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(m0), Sse.StaticCast<uint, ulong>(m3)));
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(m1), Sse.StaticCast<uint, ulong>(m2)));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_11_11_00));
#else
			t0 = Sse2.UnpackHigh(m0.AsUInt64(), m3.AsUInt64()).AsUInt32();
			t1 = Sse2.UnpackLow(m1.AsUInt64(), m2.AsUInt64()).AsUInt32();
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_11_11_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_00_10_11_01);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackLow(m0, m1);
			t1 = Sse2.UnpackHigh(m1, m2);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(t0), Sse.StaticCast<uint, ulong>(t1)));
#else
			b0 = Sse2.UnpackLow(t0.AsUInt64(), t1.AsUInt64()).AsUInt32();
#endif

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 9
			t0 = Sse2.UnpackHigh(m1, m3);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ulong, uint>(Sse2.UnpackLow(Sse.StaticCast<uint, ulong>(t0), Sse.StaticCast<uint, ulong>(m0)));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(m2), 0b_11_00_00_00));
			b0 = Sse.StaticCast<ushort, uint>(Sse2.ShuffleHigh(Sse.StaticCast<uint, ushort>(t2), 0b_01_00_11_10));
#else
			t1 = Sse2.UnpackLow(t0.AsUInt64(), m0.AsUInt64()).AsUInt32();
			t2 = Sse41.Blend(t1.AsUInt16(), m2.AsUInt16(), 0b_11_00_00_00).AsUInt32();
			b0 = Sse2.ShuffleHigh(t2.AsUInt16(), 0b_01_00_11_10).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.UnpackHigh(m0, m3);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m2), Sse.StaticCast<uint, ushort>(t0), 0b_11_11_00_00));
#else
			t1 = Sse41.Blend(m2.AsUInt16(), t0.AsUInt16(), 0b_11_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t1, 0b_00_10_01_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m2), Sse.StaticCast<uint, ushort>(m0), 0b_00_00_11_00));
#else
			t0 = Sse41.Blend(m2.AsUInt16(), m0.AsUInt16(), 0b_00_00_11_00).AsUInt32();
#endif
			t1 = Sse2.ShiftLeftLogical128BitLane(t0, 4);
#if OLD_INTRINSICS
			b0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(m3), 0b_00_00_11_11));
#else
			b0 = Sse41.Blend(t1.AsUInt16(), m3.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(m0), 0b_00_11_00_00));
#else
			t0 = Sse41.Blend(m1.AsUInt16(), m0.AsUInt16(), 0b_00_11_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t0, 0b_01_00_11_10);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			//ROUND 10
#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m0), Sse.StaticCast<uint, ushort>(m2), 0b_00_00_00_11));
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(m2), 0b_00_11_00_00));
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t1), Sse.StaticCast<uint, ushort>(t0), 0b_00_00_11_11));
#else
			t0 = Sse41.Blend(m0.AsUInt16(), m2.AsUInt16(), 0b_00_00_00_11).AsUInt32();
			t1 = Sse41.Blend(m1.AsUInt16(), m2.AsUInt16(), 0b_00_11_00_00).AsUInt32();
			t2 = Sse41.Blend(t1.AsUInt16(), t0.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_01_11_00_10);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

			t0 = Sse2.ShiftLeftLogical128BitLane(m0, 4);
#if OLD_INTRINSICS
			t1 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m1), Sse.StaticCast<uint, ushort>(t0), 0b_11_00_00_00));
#else
			t1 = Sse41.Blend(m1.AsUInt16(), t0.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t1, 0b_01_10_00_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			diagonalize(ref row1, ref row2, ref row3, ref row4);

			t0 = Sse2.UnpackHigh(m0, m3);
			t1 = Sse2.UnpackLow(m2, m3);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ulong, uint>(Sse2.UnpackHigh(Sse.StaticCast<uint, ulong>(t0), Sse.StaticCast<uint, ulong>(t1)));
#else
			t2 = Sse2.UnpackHigh(t0.AsUInt64(), t1.AsUInt64()).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_11_00_10_01);

			g1(ref row1, ref row2, ref row3, ref row4, b0, r16);

#if OLD_INTRINSICS
			t0 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(m3), Sse.StaticCast<uint, ushort>(m2), 0b_11_00_00_00));
#else
			t0 = Sse41.Blend(m3.AsUInt16(), m2.AsUInt16(), 0b_11_00_00_00).AsUInt32();
#endif
			t1 = Sse2.UnpackLow(m0, m3);
#if OLD_INTRINSICS
			t2 = Sse.StaticCast<ushort, uint>(Sse41.Blend(Sse.StaticCast<uint, ushort>(t0), Sse.StaticCast<uint, ushort>(t1), 0b_00_00_11_11));
#else
			t2 = Sse41.Blend(t0.AsUInt16(), t1.AsUInt16(), 0b_00_00_11_11).AsUInt32();
#endif
			b0 = Sse2.Shuffle(t2, 0b_00_01_10_11);

			g2(ref row1, ref row2, ref row3, ref row4, b0, r8);
			undiagonalize(ref row1, ref row2, ref row3, ref row4);

			row1 = Sse2.Xor(row1, row3);
			row2 = Sse2.Xor(row2, row4);
			row1 = Sse2.Xor(row1, Sse2.LoadVector128(s->h));
			row2 = Sse2.Xor(row2, Sse2.LoadVector128(s->h + 4));
			Sse2.Store(s->h, row1);
			Sse2.Store(s->h + 4, row2);
		}
	}
}
#endif
